version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: hrms_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: hrms_user
      POSTGRES_PASSWORD: hrms_pass
      POSTGRES_DB: hrms_db
    ports:
      - "5433:5432"
    volumes:
      - hrms_pgdata:/var/lib/postgresql/data

volumes:
  hrms_pgdata:
